### PR TITLE
[WIP] feat: Add class and prompts for issue label generator

### PR DESCRIPTION
**Pull request by MashyBasker**
# Enhance Issue Analysis and Labeling

## Overview
This pull request introduces a new module `issue_analysis.py` that provides functionality to generate issue labels and summarize issue descriptions using large language models (LLMs). The goal is to improve the process of categorizing and understanding GitHub issues, feature requests, and bug reports to facilitate better triaging and resolution.

## Changes
- Key Changes:
  - Added `IssueAnalysisGenerator` class to handle issue label generation and issue description summarization.
  - Integrated LLM-based prompts and processing logic to analyze issue titles, descriptions, and existing labels.
  - Implemented methods to generate issue labels and summarize issue descriptions.
  - Added new helper functions in `output.py` to format issue descriptions.
  - Updated `code_scan.py` to include line numbers in the output.
- New Features:
  - Ability to automatically generate relevant issue labels based on the issue title and description.
  - Summarization of issue descriptions to provide a concise overview of the problem and suggested actions.
  - Integration of LLM-based analysis to enhance the issue triaging and resolution process.
- Refactoring:
  - Reorganized and consolidated prompt templates in `issue_analysis_prompts.py`.
  - Improved logging and error handling in the `IssueAnalysisGenerator` class.
  - Optimized the `_process_issue_for_labels` and `_process_issue_for_desc` methods to reduce redundant code.

<details>
  <summary>Detailed Changes</summary>

The key changes in this pull request are:

1. **Issue Label Generation**: The `IssueAnalysisGenerator` class now provides a `generate_issue_labels` method that takes the issue title, description, and a list of existing labels, and generates a set of relevant labels using an LLM-based approach. This helps to ensure consistent and accurate labeling of issues, which is crucial for effective issue triaging and resolution.

2. **Issue Description Summarization**: The `IssueAnalysisGenerator` class also includes a `generate_issue_desc` method that summarizes the issue description, providing a concise overview of the problem and suggested actions. This feature helps project managers and developers quickly understand the essence of the issue and plan the necessary steps to address it.

3. **Prompt Handling and Optimization**: The prompt templates for issue label generation and description summarization have been consolidated and organized in the `issue_analysis_prompts.py` file. The `IssueAnalysisGenerator` class now handles the prompt generation, LLM processing, and token usage tracking more efficiently.

4. **Logging and Error Handling**: Improved logging and error handling have been implemented in the `IssueAnalysisGenerator` class to provide better visibility into the issue analysis process and handle edge cases more gracefully.

5. **Code Formatting and Consistency**: Various code formatting and consistency improvements have been made throughout the codebase, such as the use of f-strings and consistent line spacing.

</details>

> ✨ Generated with love by [Kaizen](https://cloudcode.ai) ❤️

<details>
<summary>Original Description</summary>

</details>

### CODE REVIEW

**Comment by sauravpanda** [comment]
Is this task ready for review or are we waiting on anything specific?

**Comment by MashyBasker** [comment]
The code analysis generation is done. I'm still working on adding it to the github app.

**Comment by MashyBasker** [comment]
That's great! I'll close this issue now.

**Comment by sauravpanda** [comment]
Maybe we should merge this and create a separate task for github app?

**Comment by MashyBasker** [comment]
That sounds good. I'll put this PR up for review.

**Comment by MashyBasker** [comment]
@sauravpanda Do I need to make anymore changes to this PR? I'm still working on the GitHub app integration for issue analysis and will make a PR soon.

**Review by sauravpanda — APPROVED** [review]

**Pull request merged**
